meta_actions:
  pickup:
    description: "Pick up a target object using gripper without placing it"
    sequence:
      - search_head
      - get_current_arm_position
      - open_gripper
      - move_to_open
      - detect_aruco_with_gripper_camera
      - move_down
      - close_gripper
      - move_up
      - move_away_clear_view

  place:
    description: "Place the held object at the target location and put it down"
    sequence:
      - search_head
      - get_current_arm_position
      - move_to_close
      - move_down
      - open_gripper
      - move_up
      - go_home_position

  hold:
    description: "Hold the object steady without moving location"
    sequence:
      - search_head
      - get_current_arm_position
      - open_gripper
      - move_to_open
      - detect_aruco_with_gripper_camera
      - move_down
      - close_gripper

primitives:
  open_gripper:
    description: "Open the gripper"

  close_gripper:
    description: "Close the gripper"

  move_up:
    description: "Raise the gripper vertically a bit"

  move_down:
    description: "Lower the gripper vertically a bit"

  search_head:
    description: "Pan/tilt head to search for ArUco marker"

  detect_aruco_with_gripper_camera:
    description: "Use the gripper camera to detect an ArUco marker"

  explore_area_near_target:
    description: "Move or adjust pose slightly to retry marker detection"

  get_current_arm_position:
    description: "Update current arm position"

  move_to_open:
    description: "Move to the target position with open gripper"

  go_home_position:
    description: "Move arm to the home position."
  
  move_away_clear_view:
    description: "Move arm away to clear robot's camera's view."
