markers:
  - id: 20
    name: abstract geometric artpiece

  - id: 21
    name: strong visual floral artpiece

  - id: 22
    name: black and white photograph

  - id: 23
    name: natural realism artpiece

  - id: 24
    name: abstract face artpiece

  - id: 26
    name: top left, opposite of and near the entrance and reception

  - id: 27
    name: top right, near the exit

  - id: 28
    name: top middle

  - id: 29
    name: down middle, next to and near the entrance and reception

  - id: 30
    name: down right, near the exit
