markers:
  - id: 20
    name: artpiece

  - id: 21
    name: artpiece

  - id: 22
    name: artpiece

  - id: 23
    name: artpiece

  - id: 24
    name: artpiece

  - id: 25
    name: artpiece

  - id: 26
    name: up left

  - id: 27
    name: up right

  - id: 28
    name: up middle

  - id: 29
    name: down left

  - id: 30
    name: down right

  - id: 31
    name: down middle
