markers:
  - id: 10
    name: test tube

  - id: 11
    name: 29 grams powder, the red box

  - id: 12
    name: 30 grams powder, the white box

  - id: 13
    name: 31 grams powder, the black box

  - id: 14
    name: backup teset tube

  - id: 15
    name: middle of the table

  - id: 16
    name: right of the table

  - id: 17
    name: left of the table

  - id: 18
    name: handover spot
