markers:
- id: 20
  name: onion
- id: 21
  name: pineapple
- id: 22
  name: popcorn
- id: 23
  name: potato
- id: 24
  name: durian
- id: 25
  name: handover spot
- id: 26
  name: top left, opposite of and near the entrance
- id: 27
  name: top right, near the exit, opposite of bottom left
- id: 28
  name: top middle, opposite of bottom middle
- id: 29
  name: Bottom middle, next to and near the entrance, opposite of top
    middle
- id: 30
  name: Bottom right, near the exit, opposite of top right
