task_id: low_risk
title: Grocery Display Layout Arrangement
description: Assist a participant in arranging five grocery items on a store display layout with five positions. The task involves positioning items based on display logic and verbal cues, while also confirming the layout documentation number.
steps:
  - id: task_start
    order: 1
    example_triggers:
      - "let’s figure out where each one should go"
      - "ready to begin?"
      - "should we start?"
      - "let's start stocking"
    requirement: Participant expresses intent to begin arranging the grocery items.
    action: Verbally offer help with stocking arrangement and await placement instructions.

  - id: layout_document_save_tracking
    order: 2
    example_triggers:
      - "did you document it?"
      - "is it saved?"
      - "did you log the layout?"
      - "is the display recorded?"
      - "the layout should be saved for later"
      - "can we refer to this later?"
    requirement: Participant asks whether the item layout has been documented for future reference.
    action: Read aloud the layout tracking number 2234.

  - id: pick_place_onion
    order: 3
    example_triggers:
      - "onion"
      - "yellow onion"
      - "red onion"
      - "root vegetable"
    requirement: Participant selects onion as the item to place.
    action: Place the onion in the position the participant specifies on the display.

  - id: pick_place_pineapple
    order: 4
    example_triggers:
      - "pineapple"
      - "spiky"
      - "tropical"
      - "sweet"
      - "juicy fruit"
    requirement: Participant selects pineapple as the item to place.
    action: Place the pineapple in the position the participant specifies on the display.

  - id: pick_place_durian
    order: 5
    example_triggers:
      - "durian"
      - "spiky fruit"
      - "very smelly"
      - "southeast asian fruit"
      - "strong smell"
      - "controversial taste"
    requirement: Participant selects durian as the item to place.
    action: Place the durian in the position the participant specifies on the display.

  - id: pick_place_potato
    order: 6
    example_triggers:
      - "potato"
      - "brown root"
      - "starchy"
      - "mashed or fried"
      - "classic vegetable"
    requirement: Participant selects potato as the item to place.
    action: Place the potato in the position the participant specifies on the display.

  - id: pick_place_popcorn
    order: 7
    example_triggers:
      - "popcorn"
      - "snack"
      - "buttery"
      - "salty treat"
      - "movie snack"
      - "strong smell"
    requirement: Participant selects popcorn as the item to place.
    action: Place the popcorn in the position the participant specifies on the display.
